This notebook converts the MIMIC dataset used for NCMF into a format that can be used by DCMF.

In [1]:
import pandas as pd
import numpy as np

In [2]:
data_folder = "/home/zongsien/data-fusion/datasets/"
dataset_name = "PubMed"
sample_no = 3
target_link_type = 1

In [3]:
node_file = f'sampled{sample_no}_node.dat'
link_file = f'sampled{sample_no}_link.dat'
link_test_file = f'sampled{sample_no}_link.dat.test'
label_file = f'sampled{sample_no}_label.dat'
label_test_file = f'sampled{sample_no}_label.dat.test'
meta_file = f'sampled{sample_no}_meta.dat'
info_file = f'sampled{sample_no}_info.dat'
record_file = f'sampled{sample_no}_record.dat'

In [4]:
genes_count = 2665
diseases_count = 4454
chemicals_count = 5877
species_count = 619

In [5]:
# Creating matrix from link.dat file 

In [6]:
link_train_df = pd.read_csv(data_folder + dataset_name + "/" + link_file, sep = "\t", header = None)
link_train_df.columns = ["left", "right", "link_type", "link_value"]
link_train_df.head()

left  right  link_type  link_value
0   905   1396          0           1
1   718    483          0           1
2     8    992          0           1
3    74    254          0           1
4  1257   1157          0           1

In [7]:
link_train_df.tail()

left  right  link_type  link_value
37688  13566  13277          9           1
37689  13277  13566          9           1
37690  13225  13554          9           1
37691  12996  13225          9           3
37692  13277  13528          9           1

In [8]:
link_train_df0 = link_train_df[link_train_df["link_type"] == 0]
link_train_df1 = link_train_df[link_train_df["link_type"] == 1]
link_train_df2 = link_train_df[link_train_df["link_type"] == 2]
link_train_df3 = link_train_df[link_train_df["link_type"] == 3]
link_train_df4 = link_train_df[link_train_df["link_type"] == 4]
link_train_df5 = link_train_df[link_train_df["link_type"] == 5]
link_train_df6 = link_train_df[link_train_df["link_type"] == 6]
link_train_df7 = link_train_df[link_train_df["link_type"] == 7]
link_train_df8 = link_train_df[link_train_df["link_type"] == 8]
link_train_df9 = link_train_df[link_train_df["link_type"] == 9]

In [9]:
link_train_df0.head()

left  right  link_type  link_value
0   905   1396          0           1
1   718    483          0           1
2     8    992          0           1
3    74    254          0           1
4  1257   1157          0           1

In [10]:
link_train_df0.tail()

left  right  link_type  link_value
3986  1432    910          0           1
3987   365    515          0           2
3988  2132    279          0           2
3989   841    371          0           1
3990   515    365          0           2

In [11]:
max(link_train_df0["link_value"])

376

In [12]:
gene_gene_np = np.zeros((genes_count, genes_count))
gene_gene_np.shape

(2665, 2665)

In [13]:
gene_gene_np[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [14]:
for idx, v in link_train_df0.iterrows():
    gene_gene_np[int(v["left"])][int(v["right"])] = v["link_value"]

In [15]:
gene_disease_np = np.zeros((genes_count, diseases_count))
print(gene_disease_np[1])

[0. 0. 0. ... 0. 0. 0.]


In [16]:
link_train_df1.head()

left  right  link_type  link_value
3991   829   6717          1           7
3992  1220   6367          1           2
3993  1044   3426          1           2
3994  2304   2744          1           2
3995  1042   5988          1           2

In [17]:
for idx, v in link_train_df1.iterrows():
    gene_disease_np[int(v["left"])][int(v["right"]) - genes_count] = v["link_value"]
print(gene_disease_np[1])

[0. 0. 0. ... 0. 0. 0.]


In [18]:
disease_disease_np = np.zeros((diseases_count, diseases_count))
print(disease_disease_np[0])

[0. 0. 0. ... 0. 0. 0.]


In [19]:
link_train_df2.head()

left  right  link_type  link_value
8611  6012   4049          2           1
8612  6008   5289          2           2
8613  6728   2670          2           3
8614  5990   7004          2           2
8615  6150   2670          2           1

In [20]:
for idx, v in link_train_df2.iterrows():
    disease_disease_np[int(v["left"]) - genes_count][int(v["right"]) - genes_count] = v["link_value"]
print(disease_disease_np[0])

[0. 0. 0. ... 0. 0. 0.]


In [21]:
chemical_gene_np = np.zeros((chemicals_count, genes_count))
print(chemical_gene_np[0])
print(link_train_df3.head())
for idx, v in link_train_df3.iterrows():
    chemical_gene_np[int(v["left"]) - genes_count - diseases_count][int(v["right"])] = v["link_value"]
print(chemical_gene_np[0])

[0. 0. 0. ... 0. 0. 0.]
        left  right  link_type  link_value
13948   8750   2304          3           2
13949   8216   1432          3           2
13950  10955    675          3           2
13951  12370   1096          3          13
13952  12987   1154          3           3
[0. 0. 0. ... 0. 0. 0.]


In [22]:
chemical_disease_np = np.zeros((chemicals_count, diseases_count))
print(chemical_disease_np[0])
print(link_train_df4.head())
for idx, v in link_train_df4.iterrows():
    chemical_disease_np[int(v["left"]) - genes_count - diseases_count][int(v["right"]) - genes_count] = v["link_value"]
print(chemical_disease_np[0])

[0. 0. 0. ... 0. 0. 0.]
        left  right  link_type  link_value
19158   9137   2670          4           4
19159  11018   5672          4           2
19160  12373   2670          4           4
19161  11770   3321          4           2
19162  10393   4159          4           4
[0. 0. 0. ... 0. 0. 0.]


In [23]:
chemical_chemical_np = np.zeros((chemicals_count, chemicals_count))
print(chemical_chemical_np[0])
print(link_train_df5.head())
for idx, v in link_train_df5.iterrows():
    chemical_chemical_np[int(v["left"]) - genes_count - diseases_count][int(v["right"]) - genes_count - diseases_count] = v["link_value"]
print(chemical_chemical_np[0])

[0. 0. 0. ... 0. 0. 0.]
        left  right  link_type  link_value
26755   8794  11716          5           1
26756  12608  11933          5           1
26757  11749  12365          5           5
26758  11696  11176          5          11
26759  11933  12608          5           1
[0. 0. 0. ... 0. 0. 0.]


In [24]:
chemical_species_np = np.zeros((chemicals_count, species_count))
print(chemical_species_np[0])
print(link_train_df6.head())
for idx, v in link_train_df6.iterrows():
    chemical_species_np[int(v["left"]) - genes_count - diseases_count][int(v["right"]) - genes_count - diseases_count - chemicals_count] = v["link_value"]
print(chemical_species_np[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [25]:
species_gene_np = np.zeros((species_count, genes_count))
print(species_gene_np[0])
print(link_train_df7.head())
for idx, v in link_train_df7.iterrows():
    species_gene_np[int(v["left"]) - genes_count - diseases_count - chemicals_count][int(v["right"])] = v["link_value"]
print(species_gene_np[0])

[0. 0. 0. ... 0. 0. 0.]
        left  right  link_type  link_value
36347  13610    982          7           3
36348  13216     69          7           3
36349  13239   1327          7           2
36350  13193    207          7           7
36351  13232   2538          7           2
[0. 0. 0. ... 0. 0. 0.]


In [26]:
species_disease_np = np.zeros((species_count, diseases_count))
print(species_disease_np[0])
print(link_train_df8.head())
for idx, v in link_train_df8.iterrows():
    species_disease_np[int(v["left"]) - genes_count - diseases_count - chemicals_count][int(v["right"]) - genes_count] = v["link_value"]
print(species_disease_np[0])

[0. 0. 0. ... 0. 0. 0.]
        left  right  link_type  link_value
36835  13602   5212          8           2
36836  13103   2670          8          11
36837  13283   6848          8           2
36838  13091   4224          8           2
36839  13415   4421          8           2
[0. 0. 0. ... 0. 0. 0.]


In [27]:
species_species_np = np.zeros((species_count, species_count))
print(species_species_np[0])
print(link_train_df9.head())
for idx, v in link_train_df9.iterrows():
    species_species_np[int(v["left"]) - genes_count - diseases_count - chemicals_count][int(v["right"]) - genes_count - diseases_count - chemicals_count] = v["link_value"]
print(species_species_np[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [28]:
gene_disease_test_np = np.zeros((genes_count, diseases_count))
link_test_df = pd.read_csv(data_folder + dataset_name + "/" + link_test_file, sep = "\t", header = None)
link_test_df.columns = ["left", "right", "link_value"]
link_test_df.head()

left  right  link_value
0  1432   3147           1
1  1885   3812           1
2  1260   3848           1
3   962   5077           1
4  2042   4191           1

In [29]:
for idx, v in link_test_df.iterrows():
    gene_disease_test_np[int(v["left"])][int(v["right"]) - genes_count] = v["link_value"]

In [30]:
# Rdoublets creation
Rdoublets = pd.DataFrame(columns = ["left", "right"])
Rdoublets["left"] = link_train_df1["left"].copy()
Rdoublets["left"] = Rdoublets["left"]
Rdoublets["right"] = link_train_df1["right"].copy()
Rdoublets["right"] = Rdoublets["right"] - genes_count

In [31]:
Rdoublets.head()

left  right
3991   829   4052
3992  1220   3702
3993  1044    761
3994  2304     79
3995  1042   3323

In [32]:
# getting traing and test idx
link_train_df1["indices"] = link_train_df1.apply(lambda row: int((row["left"]) * diseases_count + (row["right"] - genes_count)), axis = 1)
link_train_df1.head()

/home/zongsien/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


left  right  link_type  link_value   indices
3991   829   6717          1           7   3696418
3992  1220   6367          1           2   5437582
3993  1044   3426          1           2   4650737
3994  2304   2744          1           2  10262095
3995  1042   5988          1           2   4644391

In [33]:
# getting traing and test idx
link_test_df["indices"] = link_test_df.apply(lambda row: int((row["left"]) * diseases_count + (row["right"] - genes_count)), axis = 1)
link_test_df.head()

left  right  link_value  indices
0  1432   3147           1  6378610
1  1885   3812           1  8396937
2  1260   3848           1  5613223
3   962   5077           1  4287160
4  2042   4191           1  9096594

In [34]:
link_test_df.tail()

left  right  link_value  indices
87  1098   3839           0  4891666
88  1101   4288           0  4905477
89   958   3949           0  4268216
90   962   3813           0  4285896
91   949   4664           0  4228845

In [35]:
genes_count * diseases_count

11869910

In [36]:
# Saving matrices
import pickle

In [37]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_12_train_fold_1.pkl", "wb") as f:
    pickle.dump(gene_disease_np, f)

In [38]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_12_test_fold_1.pkl", "wb") as f:
    pickle.dump(gene_disease_test_np, f)

In [39]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_12_train_idx_1.pkl", "wb") as f:
    pickle.dump(link_train_df1["indices"].values, f)

In [40]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_12_test_idx_1.pkl", "wb") as f:
    pickle.dump(link_test_df["indices"].values, f)

In [41]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_11.pkl", "wb") as f:
    pickle.dump(gene_gene_np, f)

In [42]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_22.pkl", "wb") as f:
    pickle.dump(disease_disease_np, f)

In [43]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_31.pkl", "wb") as f:
    pickle.dump(chemical_gene_np, f)

In [44]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_32.pkl", "wb") as f:
    pickle.dump(chemical_disease_np, f)

In [45]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_33.pkl", "wb") as f:
    pickle.dump(chemical_chemical_np, f)

In [46]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_34.pkl", "wb") as f:
    pickle.dump(chemical_species_np, f)

In [47]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_41.pkl", "wb") as f:
    pickle.dump(species_gene_np, f)

In [48]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_42.pkl", "wb") as f:
    pickle.dump(species_disease_np, f)

In [49]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "X_44.pkl", "wb") as f:
    pickle.dump(species_species_np, f)

In [50]:
with open(f"../data/{dataset_name}/sample{sample_no}/" + "R_doublets_1.pkl", "wb") as f:
    pickle.dump(Rdoublets.values, f)